version: '3.3'
services:
    mysql-server:
      image: mysql:latest
      container_name: mysql-server
      environment:
        - MYSQL_ROOT_PASSWORD=root@password
      ports:
        - "3306:3306"
      restart: always

    backend-server:
      image: employee-mgmt-back
      container_name: backend-server
      build:
        context: springboot-backend
        dockerfile: Dockerfile 
      ports:
        - "8080:8080" 
      restart: always
      depends_on: 
        - mysql-server 
         
    webserver:
      image: employee-mgmt-front
      container_name: webserver
      build:
        context: react-frontend
        dockerfile: Dockerfile
      ports:
        - "80:80"
      restart: always
      depends_on:
        - backend-server


